<script setup>
</script>

<template>
  <main>
    <img style="align-self: center;" width="500px" src="../assets/JeffreyPhotoFramed.png" alt="Photo of Jeffrey Sanchez">
    <p class="questrial">I want to ask questions that bring to bear what is Latinx about American religion and in turn, what about American religion is Latinx. I seek to view this population not as an immigrant population but as essential to the definition of 'America.' To do this, I turn to the botanica, an independently owned Latinx religious store that dot neighborhoods, selling religious materials and services to practitioners. I ask how these sacred gods and spiritual entrepreneurs help scholars better historically situate Latinxs' making and remaking of sacred space and their demand for their place in the United States. By attending to this history and the histories of this space, I seek to resituate American religious history. I want to rethink the subfield of American religion and center the people known as 'Latinx' within a much longer historical frame. Rather than understanding them as marginal to the United States, I show how their religious practices are part and parcel of what we now consider 'American Religion.' I seek to view this population not as an immigrant population but as essential to the definition of 'America.' Within the four walls of a botanica lay what I believe is the best way to tell a story of US Latinx religious history. 
    </p> 
    <p>My project is informed by history and ethnography grounded in interdisciplinary methodology in Latinx and Africana studies as well as performance studies, anthropology, queer studies, and material studies. I draw critically from these fields to think about race, identity, and religion in the United States. I focus on how the religious worlds housed in the botanica make history alive in ways rendered problematic to 'accepted' history. I seek to answer what the botanica historically and currently does for the Latinx community, what the botanica means for the larger theoretical conception of Latino/a/@/x, Latine, or Latinidad, and finally, what the botanica means for the study of religion. Exploring how botánicas around the country function as sites for creation and reification of cultural and religious identities, even as they cater to a diverse clientele, we may have a fuller account of the term "Latinx religion" in America. </p>
  </main>
</template>
